### ISSUE TITLE
Backup existing tor browser directory

### ISSUE THREAD

**Issue by FrankGusto** [Whonix/tb-updater#14]
I noticed in the man page for update-torbrowser the following passage is in the description

> In case there is already a ~/.tb/tor-browser folder, it renames  it  to
  ~/.tb/tor-browser_(current  date  and  time). It extracts freshly down‐
  loaded TBB too to ~/.tb/tor-browser.

Unfortunately, this is not equated into reality, the update-torbrowser script merely trashes the existing installation of Tor Browser with no option of a backup.

Would such an option to backup as described be welcomed?

I myself treat Tor Browser installations as disposable, was just investigating possible contributions to the Whonix.

Frank

**Comment by adrelanos** [comment]
There was such a feature before.

Was disabled here:
https://github.com/Whonix/tb-updater/commit/2b6209fa4c1bac8e84d676a0aec36628bdf5f3c0

And then fully removed here:
https://github.com/Whonix/tb-updater/commit/f9440c7066bc08e6725c85c92b1db9f7ceba8740

Is it really needed? Nobody asked about it since its removal or requested that feature.

Better just update the man page / documentation / cli/gui message if there are any leftovers of that feature?

> was just investigating possible contributions to the Whonix.

There would be much better opportunities. :)
